/**
 * Generates `supabase/seed_matches.sql` — the 104-match WC2026 fixture.
 * Run after editing the groups dictionary; commit the resulting SQL.
 *
 *   node scripts/build-seed.js
 */

const fs = require('node:fs');
const path = require('node:path');

const groups = {
  A: ['Mexico', 'Poland', 'New Zealand', 'Saudi Arabia'],
  B: ['Canada', 'Belgium', 'Ecuador', 'Tunisia'],
  C: ['USA', 'Germany', 'Senegal', 'Uzbekistan'],
  D: ['Argentina', 'Croatia', 'Ivory Coast', 'Jordan'],
  E: ['France', 'Japan', 'Switzerland', 'Cape Verde'],
  F: ['Brazil', 'Netherlands', 'South Korea', 'Curaçao'],
  G: ['Portugal', 'Denmark', 'Australia', 'Panama'],
  H: ['Spain', 'Morocco', 'Paraguay', 'Haiti'],
  I: ['England', 'Norway', 'Egypt', 'New Caledonia'],
  J: ['Austria', 'Uruguay', 'Algeria', 'Jamaica'],
  K: ['Italy', 'Colombia', 'Iran', 'Ghana'],
  L: ['Türkiye', 'Scotland', 'Qatar', 'Honduras'],
};

const PAIRS = [[0,1],[2,3],[0,2],[1,3],[0,3],[1,2]];

const rows = [];
let cursor = new Date('2026-06-11T16:00:00Z');
function step(min) {
  const out = new Date(cursor.getTime()).toISOString();
  cursor = new Date(cursor.getTime() + min * 60_000);
  return out;
}

// Group stage — 72 matches
for (const [a, b] of PAIRS) {
  for (const g of Object.keys(groups)) {
    const teams = groups[g];
    rows.push({
      stage: 'Group Stage', group_name: g,
      team_home: teams[a], team_away: teams[b],
      match_date: step(180),
    });
  }
}

// R32
cursor = new Date('2026-06-28T16:00:00Z');
const r32 = [
  ['1A','3C/D/E/F'],['1C','3A/B/F/H'],['1D','2F'],['1E','3A/B/C/D'],
  ['1G','2I'],['1H','2J'],['1I','3B/E/H/L'],['1L','3E/H/I/J'],
  ['2A','2C'],['2B','2E'],['2D','2H'],['2G','2K'],
  ['1B','3G/I/J/K'],['1F','3C/D/G/I'],['1J','3F/G/H/K'],['1K','3A/B/D/E'],
];
for (const [h, a] of r32) {
  rows.push({ stage: 'Round of 32', group_name: null, team_home: h, team_away: a, match_date: step(180) });
}

// R16
cursor = new Date('2026-07-04T16:00:00Z');
for (let i = 1; i <= 8; i++) {
  rows.push({
    stage: 'Round of 16', group_name: null,
    team_home: `W R32-${i*2-1}`, team_away: `W R32-${i*2}`,
    match_date: step(360),
  });
}

// QF
cursor = new Date('2026-07-09T16:00:00Z');
for (let i = 1; i <= 4; i++) {
  rows.push({
    stage: 'Quarterfinals', group_name: null,
    team_home: `W R16-${i*2-1}`, team_away: `W R16-${i*2}`,
    match_date: step(720),
  });
}

// SF
cursor = new Date('2026-07-14T20:00:00Z');
rows.push({ stage:'Semifinals', group_name:null, team_home:'W QF-1', team_away:'W QF-2', match_date: step(1440) });
rows.push({ stage:'Semifinals', group_name:null, team_home:'W QF-3', team_away:'W QF-4', match_date: step(0) });

// Third place + Final
rows.push({ stage:'Third Place', group_name:null, team_home:'L SF-1', team_away:'L SF-2', match_date: new Date('2026-07-18T20:00:00Z').toISOString() });
rows.push({ stage:'Final',       group_name:null, team_home:'W SF-1', team_away:'W SF-2', match_date: new Date('2026-07-19T20:00:00Z').toISOString() });

function sqlStr(v) {
  if (v === null) return 'NULL';
  return "'" + String(v).replace(/'/g, "''") + "'";
}

const out = [];
out.push('-- Generated by scripts/build-seed.js — do not edit by hand');
out.push('-- 104 matches: 72 group stage + 16 R32 + 8 R16 + 4 QF + 2 SF + 3rd place + final\n');
out.push('-- Idempotent: only inserts when the matches table is empty.');
out.push("do $$");
out.push('begin');
out.push('if (select count(*) from public.matches) = 0 then');
out.push('  insert into public.matches (stage, group_name, team_home, team_away, match_date) values');
out.push(rows.map((r) =>
  `    (${sqlStr(r.stage)}, ${sqlStr(r.group_name)}, ${sqlStr(r.team_home)}, ${sqlStr(r.team_away)}, ${sqlStr(r.match_date)}::timestamptz)`,
).join(',\n') + ';');
out.push("  raise notice 'seeded % matches', " + rows.length + ';');
out.push('else');
out.push("  raise notice 'matches already seeded — skipping';");
out.push('end if;');
out.push("end $$;");

const target = path.join(__dirname, '..', 'supabase', 'seed_matches.sql');
fs.mkdirSync(path.dirname(target), { recursive: true });
fs.writeFileSync(target, out.join('\n') + '\n');
console.error(`wrote ${target} (${rows.length} matches)`);
